---
# defaults file for odoo
odoo_service_name: odoo
odoo_image: odoo:17.0
odoo_srv_port: 8069
odoo_db_service_name: odoo-db
odoo_db_image: postgres:15
odoo_db_srv_port: 5432
odoo_db_user: odoo
odoo_db_password: myodoo
odoo_network: "{{ docker_network_name }}"