services:
  icwebapp:
    image: ic-webapp:1.0
    container_name: test-ic-webapp
    ports:
      - "8080:8080"
    environment: 
      - "ODOO_URL="
      - "PGADMIN_URL="
    networks:
      - odoo-net
      
networks:
  odoo-net:
    driver: bridge 
    external: true
    name: odoo-net