services:
  web:
    image: odoo:17.0
    container_name: odoo-web
    depends_on:
      - mydb
    ports:
      - "8069:8069"
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=myodoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    networks:
      - odoo-net
  mydb:
    container_name: odoo-db
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  networks:
      - odoo-net


volumes:
  odoo-web-data:
  odoo-db-data:
networks:
  odoo-net:
    driver: bridge 
    external: true
    name: odoo-net