services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=datascientest@datascientest.io"
      - "PGADMIN_DEFAULT_PASSWORD=SuperSecret"