---
- name: projet ds
  hosts: machine-1
  become: true
  vars:
    docker_network_name: projet-ds-network
    odoo_url: "http://{{ ansible_host }}:{{ odoo_srv_port }}"
    pgadmin_url: "http://{{ ansible_host }}:{{ pgadmin_srv_port }}"
  pre_tasks:
    - name: Create docker network
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        state: present
        driver: bridge
  roles: 
    # - docker
    - odoo
    - pgadmin
    - icwebapp

